// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amldhygipvgngkpalbkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbGRoeWdpcHZnbmdrcGFsYmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NTg2NDAsImV4cCI6MjA2MjQzNDY0MH0.YaLSkT2_aZQQsQH_UJ_8OwUt9ccebHVqLmmIafGbZvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);